# Generated by Django 6.0 on 2026-09-02 14:09

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_link_project_url_experience_activity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('code', models.IntegerField(blank=True, max_length=6, null=True)),
                ('expiry_time', models.DateTimeField(default=datetime.datetime(2026, 9, 2, 14, 24, 24, 92354, tzinfo=datetime.timezone.utc))),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
