# Generated by Django 6.0 on 2026-09-02 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_tempuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempuser',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tempuser',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 2, 14, 34, 59, 349500, tzinfo=datetime.timezone.utc)),
        ),
    ]
