# Generated by Django 6.0 on 2026-09-02 16:53

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_tempuser_email_alter_tempuser_expiry_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempuser',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 2, 17, 8, 41, 882248, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='MyToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('token', models.CharField(default='8bqPID0QcpwfYUJdVibDP8pfFwD-M8iYqux-Bw8x924', max_length=32)),
                ('temp_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_tokens', to='users.tempuser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
