# Generated by Django 6.0 on 2026-09-02 18:38

import datetime
import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_tempuser_expiry_time_mytoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='avatars_thumb/'),
        ),
        migrations.AlterField(
            model_name='education',
            name='certification',
            field=models.FileField(blank=True, null=True, upload_to='certifications/', validators=[users.validators.validate_certification_size]),
        ),
        migrations.AlterField(
            model_name='mytoken',
            name='token',
            field=models.CharField(default='i0YnqRTZnffPvYFKf5MhL9xVjscG_IFWEpiC9YCZOnc', max_length=32),
        ),
        migrations.AlterField(
            model_name='project',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/', validators=[users.validators.validate_cover_image_size]),
        ),
        migrations.AlterField(
            model_name='tempuser',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 2, 18, 53, 0, 911253, tzinfo=datetime.timezone.utc)),
        ),
    ]
