# Generated by Django 6.0 on 2026-09-02 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_profile_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytoken',
            name='token',
            field=models.CharField(default='wQqf8-ArfP_Y7DAPsiQh-q-qWIh8WggSHS4lM6hyCBU', max_length=32),
        ),
        migrations.AlterField(
            model_name='tempuser',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tempuser',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 2, 18, 54, 12, 49328, tzinfo=datetime.timezone.utc)),
        ),
    ]
