# Generated by Django 6.1 on 2026-09-03 00:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_mytoken_token_alter_tempuser_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytoken',
            name='token',
            field=models.CharField(default='e8iA2ag9oNz0MAeNJZCH9Xpgos0o5H_E056TDsVx9r4', max_length=32),
        ),
        migrations.AlterField(
            model_name='tempuser',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 3, 0, 56, 41, 91584, tzinfo=datetime.timezone.utc)),
        ),
    ]
