# Generated by Django 6.1 on 2026-09-03 13:03

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_mytoken_token_alter_tempuser_expiry_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_title', models.CharField(max_length=200, unique=True)),
                ('usage_counts', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='mytoken',
            name='token',
            field=models.CharField(default='ZibE3kZ8xiiewXPjiJry1zN-FZpVuLYbw1W32AXzDzM', max_length=32),
        ),
        migrations.AlterField(
            model_name='tempuser',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 3, 13, 18, 33, 111064, tzinfo=datetime.timezone.utc)),
        ),
    ]
