# Generated by Django 6.1 on 2026-09-03 13:15

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_jobtitle_alter_mytoken_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.CharField(max_length=200, unique=True)),
                ('usage_counts', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SkillUnique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skill', models.CharField(max_length=200, unique=True)),
                ('usage_counts', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('technology', models.CharField(max_length=200, unique=True)),
                ('usage_counts', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='mytoken',
            name='token',
            field=models.CharField(default='oGcikc598qrvtkjzpP2vGxniUk1Kiivm0K_L6Om0Cbg', max_length=32),
        ),
        migrations.AlterField(
            model_name='tempuser',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 3, 13, 30, 0, 532498, tzinfo=datetime.timezone.utc)),
        ),
    ]
