# Generated by Django 6.1 on 2026-09-03 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_field_skillunique_technology_alter_mytoken_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytoken',
            name='token',
            field=models.CharField(default='KWY09bOY3vygSDCp9d-0Mq3VQsDgFgPNzhK2fr7G7NY', max_length=32),
        ),
        migrations.AlterField(
            model_name='tempuser',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 3, 13, 34, 25, 924914, tzinfo=datetime.timezone.utc)),
        ),
    ]
