# Generated by Django 6.1 on 2026-09-04 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_mytoken_token_alter_tempuser_expiry_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='telegram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mytoken',
            name='token',
            field=models.CharField(default='gcaMhec6eeDvqQ6O82pznuzkmNqpm-6SZTU6K8fa0_w', max_length=32),
        ),
        migrations.AlterField(
            model_name='tempuser',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 4, 11, 22, 20, 294663, tzinfo=datetime.timezone.utc)),
        ),
    ]
