# Generated by Django 5.2.17 on 2026-09-05 06:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_customuser_telegram_url_alter_mytoken_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytoken',
            name='token',
            field=models.CharField(default='7en49-B0xSKmq6XuK6Xo7tPdy8sl59_irCK3x79O0ho', max_length=32),
        ),
        migrations.AlterField(
            model_name='tempuser',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 5, 6, 41, 29, 826487, tzinfo=datetime.timezone.utc)),
        ),
    ]
