# Generated by Django 5.2.17 on 2026-09-05 08:28

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_mytoken_token_alter_tempuser_expiry_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytoken',
            name='token',
            field=models.CharField(default=users.models.generate_token, max_length=64),
        ),
        migrations.AlterField(
            model_name='tempuser',
            name='expiry_time',
            field=models.DateTimeField(default=users.models.default_expiry),
        ),
    ]
