# Generated by Django 5.2.17 on 2026-09-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_mytoken_token_alter_tempuser_expiry_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
