# Generated by Django 5.2.17 on 2026-09-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_skill_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
