# Generated by Django 5.2.17 on 2026-09-08 13:21

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_customuser_resume_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/', validators=[users.validators.validate_resume_file_size]),
        ),
    ]
